tools:
  external_code_coverage: true

filter:
  excluded_paths:
    - tests/*

coding_style:
  php:
    spaces:
      around_operators:
        negation: true
      other:
        after_type_cast: false
