language: php
sudo: false

php:
  - 5.3
    env: 
      - COMPOSER_OPTIONS="--prefer-dist --prefer-stable --prefer-lowest"
  - 5.4
  - 5.5
  - 5.6
    env: 
      - TEST_COVERAGE=true
  - 7.0
  - 7.1
  - hhvm

allow_failures:
  - php: hhvm

fast_finish: true

before_script:
  - /home/travis/build/facile-it/paraunit/.travis/sigsegv-extension/build-for-travis.sh
  - if [[ $TEST_COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - if [[ ! $TEST_COVERAGE ]] && [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer update --prefer-dist --prefer-stable --no-interaction $COMPOSER_OPTIONS

script:
  - bin/phpunit -v $PHPUNIT_FLAGS

after_success:
  - if [[ $TEST_COVERAGE ]]; then php bin/coveralls -v; fi
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
