language: php
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - 7.2

before_install: phpenv config-rm xdebug.ini

install: composer update --prefer-dist --prefer-stable --no-interaction

script: bin/phpunit --enforce-time-limit

jobs:
  include:
    - stage: Test
      env: XDEBUG=true
      before_install: echo "Do not remove XDEBUG"
    - env: VENDOR=prefer-lowest
      install: composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction
    - env: VENDOR=lock
      install: composer install --prefer-dist --no-interaction
    - stage: Code style, static analysis and E2E
      env: E2E=true
      install: composer install --no-dev --no-interaction
      script: src/Paraunit/Bin/paraunit run nothing
    - env: PHPSTAN=true
      script: composer phpstan
    - env: CS-FIXER=true
      script: contrib/contributing.sh 
    - stage: Coverage
      script: phpdbg -qrr bin/phpunit --enforce-time-limit --coverage-clover ./build/logs/clover.xml
      after_success:
        - php bin/coveralls -v
        - bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml --revision=$TRAVIS_COMMIT
        - bin/test-reporter

before_deploy:
  - composer update --no-dev
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - php box.phar build
  - echo $DECRYPT_KEY | gpg --passphrase-fd 0 contrib/ParaunitSigningKeys.asc.gpg && gpg --batch --yes --import contrib/ParaunitSigningKeys.asc
  - echo $SIGN_KEY | gpg --passphrase-fd 0 -u E4F5798D --armor --detach-sig paraunit.phar 
  - gpg --verify paraunit.phar.asc paraunit.phar

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - paraunit.phar
    - paraunit.phar.asc
  skip_cleanup: true
  on:
    tags: true
    php: 7.0
