language: php
sudo: false

matrix:
  include:
    - php: 5.3
      env: 
        - COMPOSER_OPTIONS="--prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: 
        - TEST_COVERAGE=true
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - /home/travis/build/facile-it/paraunit/.travis/sigsegv-extension/build-for-travis.sh
  - if [[ $TEST_COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - if [[ ! $TEST_COVERAGE ]] && [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] && [[ $TRAVIS_PHP_VERSION != '7.1' ]]; then phpenv config-rm xdebug.ini; fi
  - composer update --prefer-dist --prefer-stable --no-interaction $COMPOSER_OPTIONS

script:
  - bin/phpunit -v $PHPUNIT_FLAGS

after_success:
  - if [[ $TEST_COVERAGE ]]; then php bin/coveralls -v; fi
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
