language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
allow_failures:
  - php: nightly
  - php: hhvm
fast_finish: true

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
