language: php
sudo: false

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'
allow_failures:
  - php: 'hhvm'
env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY="2.8.x"
  - SYMFONY="3.1.x"
matrix:
  fast_finish: true
  include:
    - php: '5.6'
      env: COVERAGE=true

before_script:
  - /home/travis/build/facile-it/paraunit/.travis/sigsegv-extension/build-for-travis.sh
  - if [[ $COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - if [[ ! $COVERAGE ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit -v $PHPUNIT_FLAGS

after_success:
  - if [[ $COVERAGE ]]; then php vendor/bin/coveralls -v; fi
  - if [[ $COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
