build: false
version: '{branch}-{build}'
clone_depth: 1
skip_branch_with_pr: true

cache:
  - composer.phar
  - C:\Users\appveyor\AppData\Local\Composer\files
  - c:\php -> appveyor.yml

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET ANSICON=121x90 (121x90)

install:
## install PHP
  - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
  - cd c:\php
  - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
  - IF NOT EXIST php-7.3.14-Win32-VC15-x64.zip (appveyor DownloadFile https://windows.php.net/downloads/releases/archives/php-7.3.14-Win32-VC15-x64.zip)
  - 7z x php-7.3.14-Win32-VC15-x64.zip -y >nul
  - copy /Y php.ini-development php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo date.timezone="Europe/Rome" >> php.ini
  - echo curl.cainfo=c:\php\cacert.pem >> php.ini
## install composer and dependencies
  - cd c:\projects\paraunit
  - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/composer.phar)
  - php composer.phar self-update
  - php composer.phar remove --dev phpunit/php-invoker --no-update
  - php composer.phar update --prefer-dist --prefer-stable --no-interaction --no-progress --no-suggest --ansi 

test_script:
  - cd c:\projects\paraunit
  - bin\phpunit.bat
