clone_depth: 1
cache:
  - c:\projects\symfony\composer.phar

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET ANSICON=121x90 (121x90)

install:
## install PHP
  - mkdir c:\php && cd c:\php
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.3.29-nts-Win32-VC9-x86.zip
  - 7z x php-5.3.29-nts-Win32-VC9-x86.zip -y >nul
  - del /Q *.zip
## install composer and dependencies
  - cd c:\projects\paraunit
  - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.2.3/composer.phar)
  - php composer.phar self-update
  - php composer update --prefer-dist --prefer-stable --no-interaction

test_script:
  - cd c:\projects\paraunit
  - php bin/phpunit -v
  - php src/Paraunit/Bin/paraunit run # self-consistency test
