build: false
version: '0.8.x-{build}'
clone_depth: 1
cache:
  - composer.phar
  - C:\Users\appveyor\AppData\Local\Composer\files
  - c:\php -> appveyor.yml

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET ANSICON=121x90 (121x90)

install:
## install PHP
  - mkdir c:\php && cd c:\php
  - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.9-nts-Win32-VC14-x86.zip
  - 7z x php-7.0.9-nts-Win32-VC14-x86.zip -y >nul
  - del /Q *.zip
  - copy /Y php.ini-development php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo date.timezone="Europe/Rome" >> php.ini
  - echo curl.cainfo=c:\php\cacert.pem >> php.ini
## install composer and dependencies
  - cd c:\projects\paraunit
  - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/composer.phar)
  - php composer.phar self-update
  - php composer.phar update --prefer-dist --prefer-stable --no-interaction --no-progress --no-suggest --ansi

test_script:
  - cd c:\projects\paraunit
  - bin\phpunit.bat
