version: '3.2'

services:
  php:
    container_name: paraunit_container
    build:
      context: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Paraunit"
    volumes:
      - .:/home/paraunit/projects
      - ~/.composer:/home/paraunit/.composer
      - ./docker/config/sudoers:/etc/sudoers
      - ./docker/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/.zshrc:/root/.zshrc
      - ./docker/config/.zshrc:/home/paraunit/.zshrc
    user: paraunit
