name: CI

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php:
          - '8.1'
          - '8.0'
        dependencies: ['highest']
        experimental: [false]
        include:
          - description: 'Windows'
            os: 'windows-latest'
            php: '8.0'
          - description: 'lowest'
            os: 'ubuntu-latest'
            php: '8.0'
            dependencies: 'lowest'
            env:
              SYMFONY_DEPRECATIONS_HELPER: disabled

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ matrix.php }}${{ matrix.dependencies }} 
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer remove --dev facile-it/facile-coding-standard --no-update
        if: matrix.dependencies == 'lowest'
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: '8.0'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: locked
      - run: bin/php-cs-fixer fix --ansi --verbose --dry-run
  PHPStan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: '8.0'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: locked
      - run: bin/phpstan analyse
  End2End:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coverage-driver:
          - pcov
          - xdebug
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: '8.0'
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: ${{ matrix.coverage-driver }}
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: locked
      - run: src/Bin/paraunit run FakeDriverTest
      - run: src/Bin/paraunit coverage FakeDriverTest --text
