name: CI

on:
  pull_request: null
  push:
    branches:
      - 1.x
      - 2.x

env:
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.PRIVATE_REPO_ACCESS }}"}}'

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    env:
      SYMFONY_DEPRECATIONS_HELPER: disabled      
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php:
          - '8.1'
          - '8.2'
        dependencies: ['highest']
        coverage: ['xdebug']
        include:
          - description: 'Xdebug 2'
            coverage: 'xdebug2'
            os: 'ubuntu-latest'
            php: '8.1'
          - description: 'PCov'
            coverage: 'pcov'
            os: 'ubuntu-latest'
            php: '8.1'
          - description: 'Windows'
            coverage: 'xdebug'
            os: 'windows-latest'
            php: '8.1'
          - description: 'lowest'
            coverage: 'xdebug2'
            os: 'ubuntu-latest'
            php: '8.1'
            dependencies: 'lowest'

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
      - run: composer remove --dev facile-it/facile-coding-standard --no-update
        if: matrix.dependencies == 'lowest'
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: './coverage.xml'
          fail_ci_if_error: true
  Rector:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: ramsey/composer-install@v2
      - run: vendor/bin/rector --ansi --dry-run
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    name: Code style
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: ramsey/composer-install@v2
      - run: vendor/bin/php-cs-fixer fix --ansi --verbose --dry-run
  PHPStan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: ramsey/composer-install@v2
      - run: vendor/bin/phpstan analyse --ansi
  Psalm:
    runs-on: ubuntu-latest
    name: Psalm
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: ramsey/composer-install@v2
      - run: vendor/bin/psalm
