services:
    paraunit.command.parallel_command:
        class: Paraunit\Command\ParallelCommand
        arguments:
            - "@paraunit.filter.filter"
            - "@paraunit.runner.runner"

    paraunit.command.coverage_command:
        class: Paraunit\Command\CoverageCommand
        arguments:
            - "@paraunit.filter.filter"
            - "@paraunit.runner.runner"
            - "@event_dispatcher"
