services:
  paraunit.configuration.paraunit:
    class: Paraunit\Configuration\Paraunit

  paraunit.configuration.phpunit_bin_file:
    class: Paraunit\Configuration\PHPUnitBinFile

  paraunit.configuration.phpunit_config:
    class: Paraunit\Configuration\PHPUnitConfig
    arguments:
      - '%paraunit.phpunit_config_filename%'

  paraunit.configuration.temp_filename_factory:
    class: Paraunit\Configuration\TempFilenameFactory
    arguments:
      - "@paraunit.file.temp_directory"
