parameters:
  paraunit.coverage.clover_file_path: null
  paraunit.coverage.xml_path: null
  paraunit.coverage.html_path: null

services:
  paraunit.configuration.clover_file_path:
    class: Paraunit\Configuration\OutputFile
    arguments:
      - '%paraunit.coverage.clover_file_path%'

  paraunit.configuration.xml_path:
    class: Paraunit\Configuration\OutputPath
    arguments:
      - '%paraunit.coverage.xml_path%'

  paraunit.configuration.html_path:
    class: Paraunit\Configuration\OutputPath
    arguments:
      - '%paraunit.coverage.html_path%'

  paraunit.configuration.phpdbg_bin_file:
    class: Paraunit\Configuration\PHPDbgBinFile

  paraunit.proxy.xdebug_proxy:
    class: Paraunit\Proxy\XDebugProxy
