parameters:
  paraunit.coverage.clover_file_path: './coverage'
  paraunit.coverage.xml_path: './coverage'
  paraunit.coverage.html_path: './coverage'

services:
  paraunit.configuration.clover_file_path:
    class: Paraunit\Configuration\OutputFile
    arguments:
      - ''

  paraunit.configuration.xml_path:
    class: Paraunit\Configuration\OutputPath
    arguments:
      - ''

  paraunit.configuration.html_path:
    class: Paraunit\Configuration\OutputPath
    arguments:
      - './coverage'
