services:
  paraunit.coverage.coverage_fetcher:
    class: Paraunit\Coverage\CoverageFetcher
    arguments:
      - "@paraunit.configuration.temp_filename_factory"
      - "@paraunit.test_result.coverage_failure_container"

  paraunit.coverage.coverage_merger:
    class: Paraunit\Coverage\CoverageMerger
    arguments:
      - "@paraunit.coverage.coverage_fetcher"
    tags:
      - { name: kernel.event_listener, event: process_event.process_parsing_completed, method: onProcessParsingCompleted }

  paraunit.coverage.coverage_result:
    class: Paraunit\Coverage\CoverageResult
    arguments:
      - "@paraunit.coverage.coverage_merger"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: generateResults }

  paraunit.printer.coverage_printer:
    class: Paraunit\Printer\CoveragePrinter
    arguments:
      - "@paraunit.configuration.phpdbg_bin_file"
      - "@paraunit.proxy.xdebug_proxy"
      - "@output"
    tags:
      - { name: kernel.event_listener, event: engine_event.before_start, method: onEngineBeforeStart, priority: 100 }
