services:
  paraunit.coverage.coverage_fetcher:
    class: Paraunit\Coverage\CoverageFetcher
    arguments:
      - "@paraunit.configuration.temp_filename_factory"
      - "@paraunit.test_result.coverage_failure_container"

  paraunit.coverage.coverage_merger:
    class: Paraunit\Coverage\CoverageMerger
    arguments:
      - "@paraunit.coverage.coverage_fetcher"

  paraunit.coverage.coverage_result:
    class: Paraunit\Coverage\CoverageResult
    arguments:
      - "@paraunit.coverage.coverage_merger"

  paraunit.printer.coverage_printer:
    class: Paraunit\Printer\CoveragePrinter
    arguments:
      - "@paraunit.configuration.phpdbg_bin_file"
      - "@paraunit.proxy.xdebug_proxy"
      - "@output"
