services:
  paraunit.output.pass_container:
    class: Paraunit\Output\NullOutputContainer
    arguments:
      - "ok"
      - "PASSED"
      - "."

  paraunit.output.retry_container:
    class: Paraunit\Output\NullOutputContainer
    arguments:
      - "ok"
      - "RETRIED"
      - "A"

  paraunit.output.null_container:
    class: Paraunit\Output\NullOutputContainer

  paraunit.output.abnormal_terminated_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "abnormal"
      - "abnormal terminations (fatal errors, segfaults)"
      - "X"

  paraunit.output.error_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "error"
      - "errors"
      - "E"

  paraunit.output.failure_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "fail"
      - "failures"
      - "F"

  paraunit.output.warning_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "warning"
      - "warnings"
      - "W"

  paraunit.output.risky_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "warning"
      - "risky outcome"
      - "R"

  paraunit.output.skipped_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "skip"
      - "skipped outcome"
      - "S"

  paraunit.output.incomplete_container:
    class: Paraunit\Output\OutputContainer
    arguments:
      - "incomplete"
      - "incomplete outcome"
      - "I"
