services:
  paraunit.output_container.null:
    class: Paraunit\Printer\NullOutputContainer

  paraunit.output_container.abnormal_terminated:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "abnormal"
      - "abnormal terminations (fatal errors, segfaults)"

  paraunit.output_container.error:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "error"
      - "errors"

  paraunit.output_container.failure:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "fail"
      - "failures"

  paraunit.output_container.warning:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "warning"
      - "warnings"

  paraunit.output_container.risky:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "warning"
      - "risky outcome"

  paraunit.output_container.skipped:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "skip"
      - "skipped outcome"

  paraunit.output_container.incomplete:
    class: Paraunit\Printer\OutputContainer
    arguments:
      - "incomplete"
      - "incomplete outcome"
