services:
  ## OUTPUT PARSERS ##

  paraunit.parser.json_log_parser:
    class: Paraunit\Parser\JSONLogParser
    arguments:
      - "@paraunit.parser.json_log_fetcher"
      - "@paraunit.test_result.no_test_executed_container"
    tags:
      - { name: kernel.event_listener, event: process_event.process_terminated, method: onProcessTerminated, priority: 200 }

  paraunit.parser.json_log_fetcher:
    class: Paraunit\Parser\JSONLogFetcher
    arguments:
      - "@paraunit.configuration.json_log_filename"

  paraunit.parser.test_start_parser:
    class: Paraunit\Parser\TestStartParser

  paraunit.parser.pass_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "pass"

  paraunit.parser.retry_parser:
    class: Paraunit\Parser\RetryParser
    arguments:
      - %paraunit.max_retry_count%

  paraunit.parser.failure_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "fail"

  paraunit.parser.warning_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "warning"

  paraunit.parser.incomplete_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "error"
      - "Incomplete Test: "

  paraunit.parser.skipped_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "error"
      - "Skipped Test: "

  paraunit.parser.risky_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "error"
      - "Risky Test: "

  paraunit.parser.error_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "error"

  paraunit.parser.abnormal_terminated_parser:
    class: Paraunit\Parser\AbnormalTerminatedParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "paraunitEnd"

  paraunit.parser.unknown_result_parser:
    class: Paraunit\Parser\UnknownResultParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - ""
