services:
  ## OUTPUT PARSERS ##

  paraunit.parser.json_log_parser:
    class: Paraunit\Parser\JSON\LogParser
    arguments:
      - "@paraunit.parser.json_log_fetcher"
      - "@paraunit.test_result.no_test_executed_container"
      - "@event_dispatcher"
    calls:
      - ["addParser", ["@paraunit.parser.test_start_parser"]]
      - ["addParser", ["@paraunit.parser.pass_parser"]]
      - ["addParser", ["@paraunit.parser.retry_parser"]]
      - ["addParser", ["@paraunit.parser.incomplete_parser"]]
      - ["addParser", ["@paraunit.parser.skipped_parser"]]
      - ["addParser", ["@paraunit.parser.risky_parser"]]
      - ["addParser", ["@paraunit.parser.warning_parser"]]
      - ["addParser", ["@paraunit.parser.failure_parser"]]
      - ["addParser", ["@paraunit.parser.error_parser"]]
      - ["addParser", ["@paraunit.parser.abnormal_terminated_parser"]]
      - ["addParser", ["@paraunit.parser.unknown_result_parser"]]

  paraunit.parser.json_log_fetcher:
    class: Paraunit\Parser\JSON\LogFetcher
    arguments:
      - "@paraunit.configuration.temp_filename_factory"

  paraunit.parser.test_start_parser:
    class: Paraunit\Parser\JSON\TestStartParser

  paraunit.parser.pass_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.pass_container"
      - "pass"

  paraunit.parser.retry_parser:
    class: Paraunit\Parser\JSON\RetryParser
    arguments:
      - "@paraunit.test_result.retry_container"
      - "%paraunit.max_retry_count%"

  paraunit.parser.failure_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.failure_container"
      - "fail"

  paraunit.parser.warning_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.warning_container"
      - "warning"

  paraunit.parser.incomplete_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.incomplete_container"
      - "error"
      - "Incomplete Test: "

  paraunit.parser.skipped_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.skipped_container"
      - "error"
      - "Skipped Test: "

  paraunit.parser.risky_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.risky_container"
      - "error"
      - "Risky Test: "

  paraunit.parser.error_parser:
    class: Paraunit\Parser\JSON\GenericParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.error_container"
      - "error"

  paraunit.parser.abnormal_terminated_parser:
    class: Paraunit\Parser\JSON\AbnormalTerminatedParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.abnormal_terminated_container"
      - "paraunitEnd"

  paraunit.parser.unknown_result_parser:
    class: Paraunit\Parser\JSON\UnknownResultParser
    arguments:
      - "@paraunit.test_result.test_result_factory"
      - "@paraunit.test_result.unknown_result_container"
      - ""
