services:
  ## OUTPUT PARSERS ##

  paraunit.parser.json_log_parser:
    class: Paraunit\Parser\JSONLogParser
    arguments:
      - "@paraunit.parser.json_log_fetcher"
      - "@paraunit.output_container.abnormal_terminated"
    calls:
      - [addParser, ["@paraunit.parser.pass_parser"]]
      - [addParser, ["@paraunit.parser.retry_parser"]]
      - [addParser, ["@paraunit.parser.incomplete_parser"]]
      - [addParser, ["@paraunit.parser.skipped_parser"]]
      - [addParser, ["@paraunit.parser.risky_parser"]]
      - [addParser, ["@paraunit.parser.warning_parser"]]
      - [addParser, ["@paraunit.parser.failure_parser"]]
      - [addParser, ["@paraunit.parser.error_parser"]]
    tags:
      - { name: kernel.event_listener, event: process_event.process_terminated, method: onProcessTerminated, priority: 200 }

  paraunit.parser.json_log_fetcher:
    class: Paraunit\Parser\JSONLogFetcher
    arguments:
      - "@paraunit.configuration.json_log_filename"

  paraunit.parser.pass_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.pass"
      - "pass"

  paraunit.parser.retry_parser:
    class: Paraunit\Parser\RetryParser
    arguments:
      - "@paraunit.output_container.retry"
      - %paraunit.max_retry_count%

  paraunit.parser.failure_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.failure"
      - "fail"

  paraunit.parser.warning_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.warning"
      - "warning"

  paraunit.parser.incomplete_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.incomplete"
      - "error"
      - "Incomplete Test: "

  paraunit.parser.skipped_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.skipped"
      - "error"
      - "Skipped Test: "

  paraunit.parser.risky_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.risky"
      - "error"
      - "Risky Test: "

  paraunit.parser.error_parser:
    class: Paraunit\Parser\AbstractParser
    arguments:
      - "@paraunit.output_container.error"
      - "error"

  paraunit.parser.test_result_parser:
    class: Paraunit\Parser\TestResultsParser
