services:
  paraunit.printer.shark_printer:
    class: Paraunit\Printer\SharkPrinter
    tags:
      - { name: kernel.event_listener, event: engine_event.before_start, method: onEngineStart }

  paraunit.printer.process_printer:
    class: Paraunit\Printer\ProcessPrinter
    arguments:
      - "@paraunit.printer.single_result_formatter"
    tags:
      - { name: kernel.event_listener, event: process_event.process_terminated, method: onProcessTerminated, priority: 100 }

  paraunit.printer.final_printer:
    class: Paraunit\Printer\FinalPrinter
    arguments:
      - "@paraunit.parser.json_log_parser"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: onEngineEnd }

  paraunit.printer.console_formatter:
    class: Paraunit\Printer\ConsoleFormatter
    tags:
      - { name: kernel.event_listener, event: engine_event.before_start, method: onEngineStart }

  paraunit.printer.single_result_formatter:
    class: Paraunit\Printer\SingleResultFormatter
    arguments:
     - "@paraunit.parser.json_log_parser"
