services:
  paraunit.printer.shark_printer:
    class: Paraunit\Printer\SharkPrinter
    tags:
      - { name: kernel.event_listener, event: engine_event.before_start, method: onEngineBeforeStart, priority: 1000 }

  paraunit.printer.process_printer:
    class: Paraunit\Printer\ProcessPrinter
    arguments:
      - "@paraunit.printer.single_result_formatter"
    tags:
      - { name: kernel.event_listener, event: process_event.process_terminated, method: onProcessTerminated, priority: 100 }

  paraunit.printer.final_printer:
    class: Paraunit\Printer\FinalPrinter
    arguments:
      - "@paraunit.test_result.test_result_list"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: onEngineEnd, priority: 300 }

  paraunit.printer.failures_printer:
    class: Paraunit\Printer\FailuresPrinter
    arguments:
      - "@paraunit.test_result.test_result_list"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: onEngineEnd, priority: 200 }

  paraunit.printer.files_recap_printer:
    class: Paraunit\Printer\FilesRecapPrinter
    arguments:
      - "@paraunit.test_result.test_result_list"
    tags:
      - { name: kernel.event_listener, event: engine_event.end, method: onEngineEnd, priority: 100 }

  paraunit.printer.console_formatter:
    class: Paraunit\Printer\ConsoleFormatter
    tags:
      - { name: kernel.event_listener, event: engine_event.before_start, method: onEngineStart }

  paraunit.printer.single_result_formatter:
    class: Paraunit\Printer\SingleResultFormatter
    arguments:
     - "@paraunit.test_result.test_result_list"
