services:
  paraunit.printer.abstract_printer:
    class: Paraunit\Printer\AbstractPrinter
    abstract: true
    arguments:
      - "@output"

  paraunit.printer.abstract_final_printer:
    class: Paraunit\Printer\AbstractPrinter
    abstract: true
    arguments:
      - "@paraunit.test_result.test_result_list"
      - "@output"

  paraunit.printer.shark_printer:
    class: Paraunit\Printer\SharkPrinter
    parent: paraunit.printer.abstract_printer

  paraunit.printer.process_printer:
    class: Paraunit\Printer\ProcessPrinter
    arguments:
      - "@paraunit.printer.single_result_formatter"
      - "@output"

  paraunit.printer.final_printer:
    class: Paraunit\Printer\FinalPrinter
    parent: paraunit.printer.abstract_final_printer

  paraunit.printer.failures_printer:
    class: Paraunit\Printer\FailuresPrinter
    parent: paraunit.printer.abstract_final_printer

  paraunit.printer.files_recap_printer:
    class: Paraunit\Printer\FilesRecapPrinter
    parent: paraunit.printer.abstract_final_printer

  paraunit.printer.console_formatter:
    class: Paraunit\Printer\ConsoleFormatter
    parent: paraunit.printer.abstract_printer

  paraunit.printer.single_result_formatter:
    class: Paraunit\Printer\SingleResultFormatter
    arguments:
      - "@paraunit.test_result.test_result_list"
