services:
  paraunit.process.process_factory:
    class: Paraunit\Process\ProcessBuilderFactory
    arguments:
      - "@paraunit.process.command_line"
      - "@paraunit.configuration.phpunit_config"
      - "@paraunit.configuration.temp_filename_factory"

  paraunit.process.command_line:
    class: Paraunit\Process\CommandLine
    arguments:
      - "@paraunit.configuration.phpunit_bin_file"
