services:
  paraunit.process.process_factory:
    class: Paraunit\Process\ProcessBuilderFactory
    arguments:
      - "@paraunit.process.command_line_with_coverage"
      - "@paraunit.configuration.phpunit_config"
      - "@paraunit.configuration.temp_filename_factory"

  paraunit.process.command_line_with_coverage:
    class: Paraunit\Process\CommandLineWithCoverage
    arguments:
      - "@paraunit.configuration.phpunit_bin_file"
      - "@paraunit.configuration.phpdbg_bin_file"
      - "@paraunit.configuration.temp_filename_factory"
