services:
  paraunit.process.process_factory:
    class: Paraunit\Process\ProcessFactory
    arguments:
      - "@paraunit.process.test_command_line"

  paraunit.process.test_command_line:
    class: Paraunit\Process\TestCommandLine
    arguments:
      - "@paraunit.configuration.phpunit_bin_file"
