services:
  paraunit.runner.runner:
    class: Paraunit\Runner\Runner
    arguments:
      - "@event_dispatcher"
      - "@paraunit.process.process_factory"
      - "@paraunit.filter.filter"
      - "@paraunit.runner.pipeline_collection"
    tags:
      - { name: kernel.event_listener, event: process_event.process_parsing_completed, method: onProcessParsingCompleted }

  paraunit.runner.pipeline_collection:
    class: Paraunit\Runner\PipelineCollection
    arguments:
      - "@paraunit.runner.pipeline_factory"
      - "%paraunit.max_process_count%"

  paraunit.runner.pipeline_factory:
    class: Paraunit\Runner\PipelineFactory
    arguments:
      - "@event_dispatcher"
