parameters:
  paraunit.version: "0.5.1"
  paraunit.max_retry_count: 3
  paraunit.default_max_process: 10
  kernel.root_dir: 'src'

services:
  paraunit.application:
    class: Symfony\Component\Console\Application
    arguments:
      - 'Paraunit'
      - %paraunit.version%
    calls:
      - [add, ["@paraunit.command.parallel_command"]]
      - [add, ["@paraunit.command.coverage_command"]]

  paraunit.filter.filter:
    class: Paraunit\Filter\Filter
    arguments:
      - "@paraunit.proxy.phpunit_util_xml_proxy"
      - "@phpunit.file_iterator_facade"

  paraunit.runner.runner:
    class: Paraunit\Runner\Runner
    arguments:
      - "@event_dispatcher"
      - "@paraunit.process.process_factory"
      - %paraunit.default_max_process%

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    arguments:
      - "@service_container"

  ## EXTERNAL DEPs -- proxies ##

  paraunit.proxy.phpunit_util_xml_proxy:
    class: Paraunit\Proxy\PHPUnitUtilXMLProxy

  phpunit.file_iterator_facade:
    class: \File_Iterator_Facade
