parameters:
  paraunit.max_retry_count: 3
  kernel.root_dir: 'src'

services:
  paraunit.filter.filter:
    class: Paraunit\Filter\Filter
    arguments:
      - "@paraunit.proxy.phpunit_util_xml_proxy"
      - "@phpunit.file_iterator_facade"
      - "@paraunit.configuration.phpunit_config"
      - "%paraunit.testsuite%"
      - "%paraunit.string_filter%"

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    arguments:
      - "@service_container"

  ## EXTERNAL DEPs -- proxies ##

  paraunit.proxy.phpunit_util_xml_proxy:
    class: Paraunit\Proxy\PHPUnitUtilXMLProxy

  phpunit.file_iterator_facade:
    class: \File_Iterator_Facade
