services:
  paraunit.test_result.no_test_executed_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.no_test_executed_format"

  paraunit.test_result.coverage_failure_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.coverage_failure_format"

  paraunit.test_result.pass_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.pass_test_result_format"

  paraunit.test_result.retry_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.retry_test_result_format"

  paraunit.test_result.incomplete_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.incomplete_test_result_format"

  paraunit.test_result.skipped_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.skipped_test_result_format"

  paraunit.test_result.risky_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.risky_test_result_format"

  paraunit.test_result.warning_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.warning_test_result_format"

  paraunit.test_result.failure_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.failure_test_result_format"

  paraunit.test_result.error_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.error_test_result_format"

  paraunit.test_result.abnormal_terminated_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.abnormal_terminated_test_result_format"

  paraunit.test_result.unknown_result_container:
    class: Paraunit\TestResult\TestResultContainer
    arguments:
      - "@paraunit.test_result.unknown_result_format"
